const games={
 quest:[
  {s:'Mia usually ___ to school by bike.',a:['rides','is riding','has ridden'],c:0,e:'“Usually” shows a routine — use Present Simple.'},
  {s:'Look! The castle gates ___ now.',a:['open','are opening','have opened'],c:1,e:'“Look” and “now” point to Present Continuous.'},
  {s:'We ___ three magic crystals so far.',a:['collect','are collecting','have collected'],c:2,e:'“So far” connects the past to now — Present Perfect.'},
  {s:'The moon ___ brightly every night.',a:['shines','is shining','has shone'],c:0,e:'“Every night” describes a repeated fact.'},
  {s:'I ___ this mysterious map before.',a:['see','am seeing','have seen'],c:2,e:'“Before” with life experience takes Present Perfect.'}],
 chase:[
  {s:'Quick! The time thief ___ away!',a:['runs','is running','has run'],c:1,e:'It is happening right now — Present Continuous.'},
  {s:'Leo ___ his hoverboard every weekend.',a:['rides','is riding','has ridden'],c:0,e:'“Every weekend” signals Present Simple.'},
  {s:'They ___ two checkpoints already.',a:['pass','are passing','have passed'],c:2,e:'“Already” highlights a completed result now.'},
  {s:'Watch out! A drone ___ towards us.',a:['flies','is flying','has flown'],c:1,e:'This action is in progress now.'},
  {s:'My team never ___ a race.',a:['loses','is losing','has lost'],c:2,e:'Life experience with “never” uses Present Perfect.'}],
 mystery:[
  {s:'Detective Luna always ___ every clue.',a:['checks','is checking','has checked'],c:0,e:'“Always” describes a regular habit.'},
  {s:'Someone ___ the library window!',a:['breaks','is breaking','has broken'],c:2,e:'We see a present result of a completed action.'},
  {s:'The old clock ___ strangely at the moment.',a:['ticks','is ticking','has ticked'],c:1,e:'“At the moment” signals Present Continuous.'},
  {s:'I ___ this symbol in two other rooms.',a:['find','am finding','have found'],c:2,e:'An experience/result up to now uses Present Perfect.'},
  {s:'The librarian ___ the doors at nine every day.',a:['locks','is locking','has locked'],c:0,e:'A timetable or routine uses Present Simple.'}]
};
let game='quest',q=0,score=0,streak=0,soundOn=true,totalXp=Number(localStorage.getItem('lunaXp')||0),answered=Number(localStorage.getItem('lunaAnswered')||0),cycleXp=Number(localStorage.getItem('lunaCycleXp')||0),completed=new Set(JSON.parse(localStorage.getItem('lunaCompleted')||'[]')),ctx;
const $=s=>document.querySelector(s),dialog=$('#gameDialog');
function tone(freq,duration=.12,type='sine'){if(!soundOn)return;ctx??=new AudioContext();const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.09,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+duration)}
function sync(){ $('#totalXp').textContent=totalXp;$('#answeredCount').textContent=answered;$('#progressFill').style.width=`${Math.min(answered%20/20*100,100)}%` }
function openGame(name){game=name;q=0;score=0;streak=0;$('#gameTag').textContent=name.toUpperCase();$('.game-modal').className=`game-modal theme-${name}`;$('#playScreen').hidden=false;$('#resultScreen').hidden=true;dialog.showModal();render();tone(520,.16)}
function render(){const x=games[game][q];$('#questionNumber').textContent=`QUESTION ${q+1} OF ${games[game].length}`;$('#sentence').textContent=x.s;$('#questionBar').style.width=`${q/games[game].length*100}%`;$('#score').textContent=score;$('#streak').textContent=streak;$('#feedback').textContent='';$('#feedback').className='feedback';$('#nextQuestion').style.display='none';$('#answers').innerHTML=x.a.map((a,i)=>`<button class="answer" data-i="${i}"><span>${String.fromCharCode(65+i)}.</span> ${a}</button>`).join('');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>choose(Number(b.dataset.i)))}
function choose(i){const x=games[game][q],buttons=[...document.querySelectorAll('.answer')];buttons.forEach(b=>b.disabled=true);buttons[x.c].classList.add('correct');answered++;if(i===x.c){score+=100+streak*20;streak++;$('#feedback').textContent=`Correct! ${x.e}`;$('#feedback').classList.add('good');tone(660,.12);setTimeout(()=>tone(880,.16),90)}else{buttons[i].classList.add('wrong');streak=0;$('#feedback').textContent=`Not quite. ${x.e}`;$('#feedback').classList.add('bad');tone(180,.25,'triangle')}$('#score').textContent=score;$('#streak').textContent=streak;$('#nextQuestion').style.display='flex';localStorage.setItem('lunaAnswered',answered);sync()}
function next(){if(++q<games[game].length)render();else finish()}
function finish(){const earned=Math.round(score/10);if(!completed.has(game)){completed.add(game);cycleXp+=earned}const cycleComplete=completed.size===3;if(cycleComplete){totalXp+=cycleXp;localStorage.setItem('lunaXp',totalXp);completed=new Set;cycleXp=0}localStorage.setItem('lunaCompleted',JSON.stringify([...completed]));localStorage.setItem('lunaCycleXp',cycleXp);sync();$('#questionBar').style.width='100%';$('#playScreen').hidden=true;$('#resultScreen').hidden=false;$('#finalScore').textContent=earned;$('#resultTitle').textContent=cycleComplete?'All three adventures complete!':score>=450?'Tense master!':score>=300?'Brilliant work!':'Adventure complete!';const left=3-completed.size;$('#resultCopy').textContent=cycleComplete?`You scored ${score} points. Your full-cycle XP has been added to the main page!`:`You scored ${score} points. Complete ${left} more ${left===1?'game':'games'} to add all cycle XP to the main score.`;tone(523,.12);setTimeout(()=>tone(659,.12),110);setTimeout(()=>tone(784,.25),220)}
document.querySelectorAll('.game-card').forEach(c=>{c.onclick=()=>openGame(c.dataset.game);c.onkeydown=e=>{if(e.key==='Enter')openGame(c.dataset.game)}});$('#nextQuestion').onclick=next;$('#playAgain').onclick=()=>openGame(game);$('#closeGame').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};$('#soundToggle').onclick=e=>{soundOn=!soundOn;e.currentTarget.classList.toggle('sound-off',!soundOn);e.currentTarget.textContent=soundOn?'♪':'×';e.currentTarget.setAttribute('aria-label',soundOn?'Turn sound off':'Turn sound on');tone(500)};sync();
