const regularQuestionRender=render;
const chaseSentences=['Quick! The time thief is running away!','Leo rides his hoverboard every weekend.','They have already passed two checkpoints.','Watch out! The bat is flying towards us.','The team has never lost the race.'];
function shuffledWords(words,seed){const result=words.map((word,index)=>({word,index}));for(let i=result.length-1;i>0;i--){const j=(seed*7+i*3+1)%(i+1);[result[i],result[j]]=[result[j],result[i]]}if(result.every((item,index)=>item.index===index))result.push(result.shift());return result}
function renderSentenceBuilder(){
 document.querySelectorAll('.flying-bat').forEach(bat=>bat.remove());
 const sentence=chaseSentences[q],words=sentence.split(' '),shuffled=shuffledWords(words,q+3),chosen=[];let selectedPosition=-1;const cat=$('#lunaPlayer');cat.className='luna-walker';cat.style.setProperty('--target','50%');$('#gameRoom').className='game-room room-chase builder-room';$('#lunaThought').textContent='Let me build it!';$('#questionNumber').textContent=`SENTENCE ${q+1} OF ${games.chase.length}`;$('#sentence').textContent='Build the sentence';$('#questionBar').style.width=`${q/games.chase.length*100}%`;$('#correctCount').textContent=`${correct}/5`;$('#runGems').textContent=correct;$('#streak').textContent=streak;$('#feedback').textContent='';$('#feedback').className='feedback';$('#combo').textContent='';$('#nextQuestion').style.display='none';const answers=$('#answers');answers.className='answers builder-zone';answers.innerHTML='<div class="sentence-line" id="sentenceLine"><span>Tap the words, then swap any two words to fix the order</span></div><div class="word-bank" id="wordBank"></div><button class="check-sentence" id="checkSentence" disabled>Check sentence</button>';const bank=$('#wordBank');bank.innerHTML=shuffled.map((item,index)=>`<button class="word-token" data-bank="${index}" data-original="${item.index}">${item.word}</button>`).join('');const checkButton=$('#checkSentence');
 function returnToBank(position){const [item]=chosen.splice(position,1);item.button.disabled=false;item.button.classList.remove('used');selectedPosition=-1;paint()}
 function paint(){const line=$('#sentenceLine');checkButton.disabled=chosen.length!==words.length;if(!chosen.length){line.innerHTML='<span>Tap or drag words here in the correct order</span>';return}line.innerHTML=chosen.map((item,index)=>`<button draggable="true" title="Drag to swap · tap twice to return" class="placed-word ${item.word===words[index]?'word-correct':'word-wrong'} ${selectedPosition===index?'swap-selected':''}" data-position="${index}">${item.word}<small>↩</small></button>`).join('');line.querySelectorAll('.placed-word').forEach(button=>{button.onclick=()=>{const position=Number(button.dataset.position);if(selectedPosition<0){selectedPosition=position;paint();return}if(selectedPosition===position){returnToBank(position);return}[chosen[selectedPosition],chosen[position]]=[chosen[position],chosen[selectedPosition]];selectedPosition=-1;paint()};button.ondragstart=event=>{event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',button.dataset.position);button.classList.add('dragging-word')};button.ondragend=()=>button.classList.remove('dragging-word');button.ondragover=event=>{event.preventDefault();button.classList.add('word-drop-target')};button.ondragleave=()=>button.classList.remove('word-drop-target');button.ondrop=event=>{event.preventDefault();const from=Number(event.dataTransfer.getData('text/plain')),to=Number(button.dataset.position);button.classList.remove('word-drop-target');if(Number.isInteger(from)&&from!==to){[chosen[from],chosen[to]]=[chosen[to],chosen[from]];selectedPosition=-1;paint()}}})}
 bank.ondragover=event=>{event.preventDefault();bank.classList.add('bank-drop-target')};bank.ondragleave=()=>bank.classList.remove('bank-drop-target');bank.ondrop=event=>{event.preventDefault();bank.classList.remove('bank-drop-target');const position=Number(event.dataTransfer.getData('text/plain'));if(Number.isInteger(position)&&chosen[position])returnToBank(position)};bank.onclick=event=>{if(event.target===bank&&selectedPosition>=0)returnToBank(selectedPosition)};bank.querySelectorAll('.word-token').forEach(button=>button.onclick=()=>{if(button.disabled)return;button.disabled=true;button.classList.add('used');chosen.push({word:button.textContent,original:Number(button.dataset.original),button});paint()});checkButton.onclick=()=>checkBuiltSentence(words,chosen,sentence,checkButton)
}
function checkBuiltSentence(words,chosen,sentence,checkButton){if(checkButton.disabled)return;checkButton.disabled=true;document.querySelectorAll('.placed-word,.word-token').forEach(button=>button.disabled=true);state.answered++;const allCorrect=chosen.every((item,index)=>item.word===words[index]),cat=$('#lunaPlayer');cat.classList.add('walking');if(allCorrect){correct++;score+=100+streak*25;streak++;cat.classList.add('happy');$('#lunaThought').textContent='Purr-fect sentence!';$('#feedback').textContent='Correct! Every word is in the right place.';$('#feedback').classList.add('good');if(streak>=2)$('#combo').textContent=`${streak}× PERFECT COMBO!`;if(q===3){const bat=document.createElement('img');bat.src='assets/magic-bat.png';bat.alt='A magical bat flies into the room';bat.className='flying-bat';$('#gameRoom').append(bat)}setTimeout(()=>speak(sentence),650);tone(660);setTimeout(()=>tone(880,.18),90)}else{streak=0;cat.classList.add('sad');$('#lunaThought').textContent='Let me try this mission again!';$('#feedback').textContent=`Not quite. The correct sentence is: ${sentence}`;$('#feedback').classList.add('bad');tone(180,.25,'triangle')}$('#correctCount').textContent=`${correct}/5`;$('#runGems').textContent=correct;$('#streak').textContent=streak;$('#nextQuestion').style.display='flex';save()}
render=function(){if(game==='chase')renderSentenceBuilder();else{$('#answers').className='answers';regularQuestionRender()}};
